# Generated by Django 5.0.1 on 2024-02-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.ImageField(null=True, upload_to='images/')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('book_description', models.TextField()),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.categorymodel')),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.usermodel')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
