# Generated by Django 5.0.1 on 2024-02-20 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_alter_bookmodel_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_name', models.TextField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.bookmodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
