# Generated by Django 5.0.1 on 2024-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0004_reviewmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_name',
            field=models.TextField(),
        ),
    ]
